### ISSUE TITLE
Tony Agression values and hearing radar interaction and changes

### ISSUE THREAD

**Issue by Jkirby243** [Todd-Stein/KSUGameDev2023Team1#11]

**Comment by Jkirby243** [comment]
Add in Aggression value changes based on a scale with Sight or collision increasing by a high multiplier, and simple distractions being increasing by constant small multiplier. 

These aggression changes should correlate to Tony's hearing radar, along with Tonys chase speed towards a investigation point.   He should also take less time at investigation points when he is aggressive as well. There should also be future flat increase of aggression values after tony leaves hunt mode. This can simply be a function for now since we are working separately.

**Comment by jel2658** [comment]
- Sound events call one function that increases aggression by noise level.
- Sight increases by 10, and continues to increase while player stays in sight.
- Simple aggression increase function created for hunt and future use.
- Tony's hearing radar increases as his aggression increases.
