### ISSUE TITLE
Tony room changer

### ISSUE THREAD

**Issue by Jkirby243** [Todd-Stein/KSUGameDev2023Team1#19]

**Comment by jel2658** [comment]
Tony moves to the new room and patrols that room when the Player moves into that area.

**Comment by Jkirby243** [comment]
Add in a trigger so whenever the player enter the room it will have tony then follow to that new room and begin new pathing so that he does not just stay in the same room forever

**Comment by jel2658** [comment]
- Issue exists as a script to attach to game objects that count as checkpoints for Tony's patrolling.
