### ISSUE TITLE
Idle pathfinding

### ISSUE THREAD

**Issue by Jkirby243** [Todd-Stein/KSUGameDev2023Team1#2]
Initial pathfinding for Tony allowing him to traverse a enclosed open area that will allow for him to go in around obstacles in his way and loop a path.

If time also begin to implement the ability to have the looping path as a default and then break from this to go to a assigned location within the enclosed area in the same manner of a pathing while avoiding obstructions.

**Comment by jel2658** [comment]
Whoops
