### ISSUE TITLE
Tony hurts the player, and make it so tony calls the player visuals

### ISSUE THREAD

**Issue by Jkirby243** [Todd-Stein/KSUGameDev2023Team1#29]
Add in a reference to the player health script in the tony script and call it when tony gets to the player

**Comment by Jkirby243** [comment]
Add in the references to the scripts from the player, and call the damage function for the player health as well as the function for starting and stopping the the visuals for hunt mode.

**Comment by Jkirby243** [comment]
Health is added, player visuals are not.

**Comment by jel2658** [comment]
- Damage function creates visuals for the player.
