### ISSUE TITLE
Checkpoint system

### ISSUE THREAD

**Issue by Jkirby243** [Todd-Stein/KSUGameDev2023Team1#40]
Checkpoint system will need to grab all the values of tony the player, their position, the world state, and the alert state of tony. This will have to be stored the moment the new checkpoint is made the primary checkpoint

**Comment by jel2658** [comment]
- Checkpoint stores Tony's position and aggression.
- Checkpoint stores player's position.

**Comment by jel2658** [comment]
- Checkpoint stores player's health.
- Checkpoint disables previous checkpoint.
- Checkpoint reloads Tony and Player on death.
