### ISSUE TITLE
Create the environment props as prefabs and items

### ISSUE THREAD

**Issue by Jkirby243** [Todd-Stein/KSUGameDev2023Team1#49]
Download the unity packages and get them all setup for collision and goggle systems so that they will work fine when placed in the scene.

If you have time go ahead and make some interactable items with sounds and throwables with sounds if you have time!

Rooms that will be in the game, Cafeteria, science lab, office, horrors beyond comprehension

**Comment by jel2658** [comment]
- Cafeteria being actively worked on in Tony Team Models branch.
