### ISSUE TITLE
Tony spotting player

### ISSUE THREAD

**Issue by Jkirby243** [Todd-Stein/KSUGameDev2023Team1#6]
Have a conecollider interact with the player based on a tag system so that it will only occur when the goggles area active. The tag will also allow us to add a tag to a player object.

**Comment by jel2658** [comment]
- Possibly remodel cone of vision to be flat above the floor.

**Comment by jel2658** [comment]
- Just need to check if goggles are active to chase player now.

**Comment by Jkirby243** [comment]
DOne
